# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import request_pb2 as request__pb2
import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x11pdpfeedaggregator\x1a\x1cgoogle/protobuf/struct.proto\x1a\rrequest.proto\x1a\x0eresponse.proto2x\n\x0ePdpFeedHandler\x12\x66\n\x0c\x46\x65tchPdpFeed\x12).pdpfeedaggregator.RecommendationsRequest\x1a).pdpfeedaggregator.RecommendationResponse\"\x00\x42@\n4com.meesho.ml.feedaggregator.pdpclient.grpc.servicesP\x01Z\x06../pdpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n4com.meesho.ml.feedaggregator.pdpclient.grpc.servicesP\001Z\006../pdp'
  _globals['_PDPFEEDHANDLER']._serialized_start=93
  _globals['_PDPFEEDHANDLER']._serialized_end=213
# @@protoc_insertion_point(module_scope)
