# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pricing_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pricing_service.proto\"\x92\x02\n\rEntityQueries\x12\r\n\x05label\x18\x01 \x01(\t\x12$\n\x03ids\x18\x02 \x03(\x0b\x32\x17.EntityQueries.EntityId\x12\x33\n\rfeatureGroups\x18\x03 \x03(\x0b\x32\x1c.EntityQueries.FeatureGroups\x1a\x65\n\x08\x45ntityId\x12/\n\x04keys\x18\x01 \x03(\x0b\x32!.EntityQueries.EntityId.EntityKey\x1a(\n\tEntityKey\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1a\x30\n\rFeatureGroups\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\t\x12\r\n\x05label\x18\x02 \x01(\t\"r\n\rEntityPayload\x12\x13\n\x0b\x65ntityLabel\x18\x01 \x01(\t\x12!\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x13.EntityPayload.Data\x12\x0f\n\x07keySize\x18\x03 \x01(\x05\x1a\x18\n\x04\x44\x61ta\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\t2V\n\x1ePricingFeatureRetrievalService\x12\x34\n\x10retrieveFeatures\x12\x0e.EntityQueries\x1a\x0e.EntityPayload\"\x00\x42\tZ\x07../grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007../grpc'
  _globals['_ENTITYQUERIES']._serialized_start=26
  _globals['_ENTITYQUERIES']._serialized_end=300
  _globals['_ENTITYQUERIES_ENTITYID']._serialized_start=149
  _globals['_ENTITYQUERIES_ENTITYID']._serialized_end=250
  _globals['_ENTITYQUERIES_ENTITYID_ENTITYKEY']._serialized_start=210
  _globals['_ENTITYQUERIES_ENTITYID_ENTITYKEY']._serialized_end=250
  _globals['_ENTITYQUERIES_FEATUREGROUPS']._serialized_start=252
  _globals['_ENTITYQUERIES_FEATUREGROUPS']._serialized_end=300
  _globals['_ENTITYPAYLOAD']._serialized_start=302
  _globals['_ENTITYPAYLOAD']._serialized_end=416
  _globals['_ENTITYPAYLOAD_DATA']._serialized_start=392
  _globals['_ENTITYPAYLOAD_DATA']._serialized_end=416
  _globals['_PRICINGFEATURERETRIEVALSERVICE']._serialized_start=418
  _globals['_PRICINGFEATURERETRIEVALSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
