# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: request.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrequest.proto\x12\x11pdpfeedaggregator\"\xa1\x01\n\x16RecommendationsRequest\x12\x0e\n\x06\x63ursor\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x11\n\tfeed_type\x18\x04 \x01(\t\x12\x14\n\x0c\x66\x65\x65\x64_context\x18\x05 \x01(\t\x12\x12\n\ncatalog_id\x18\x06 \x01(\x05\x12\x1b\n\x13sub_sub_category_id\x18\x07 \x01(\x05\x42<\n0com.meesho.ml.feedaggregator.pdpclient.grpc.dtosP\x01Z\x06../pdpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.meesho.ml.feedaggregator.pdpclient.grpc.dtosP\001Z\006../pdp'
  _globals['_RECOMMENDATIONSREQUEST']._serialized_start=37
  _globals['_RECOMMENDATIONSREQUEST']._serialized_end=198
# @@protoc_insertion_point(module_scope)
